#!/bin/bash

# Test MON86 stub on host

host/mon86-stub <test-mon86-in.txt >test-mon86-out.txt

diff test-mon86-ref.txt test-mon86-out.txt
if (( $? > 0 )); then
	echo "FAILED"
	else
	echo "PASSED"
	fi
